# frozen_string_literal: true

ruby '~> 2.5.3'
source 'http://rubygems.org'

gem 'httparty'
gem 'json'
# bundle exec mutant --include lib --require 'searcher.rb' --use rspec Class
gem 'mutant-rspec'
gem 'pry'
gem 'pry-byebug'
gem 'rspec'
gem 'rubocop'
